config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'

  get 'reviews/create'

  get 'users/new'

  get 'users/create'

  get 'welcome/index'

  resources :movies do 
    resources :reviews, only: [:new, :create]
  end

  resources :users, only: [:new, :create] do
    resource :profile, to: 'users#show'
  end

  resource :session, only: [:new, :create, :destroy]

  namespace :admin do
    resources :users
  end
  

  root 'welcome#index'

end

app/models/movie.rb
class Movie < ActiveRecord::Base

  mount_uploader :image, ImageUploader

  has_many :reviews
  
  validates :title,
    presence: true

  validates :director,
    presence: true

  validates :description,
    presence: true

  validates :runtime_in_minutes,
    presence: true,
    numericality: { integer_only: true }

  validates :poster_image_url,
    presence: true

  validates :release_date,
    presence: true

  validate :release_date_is_in_the_past

  def self.search(search)
    if search
      where('title LIKE :search OR director LIKE :search', search: "%#{search}%")
    end
  end

  # search by duration

  def self.search_duration(search)
    case search
    when "Under 90 minutes"
      search_results = Movie.less_than(90)
    when "Between 90 and 120 minutes"
      search_results = Movie.less_than(120).greater_than(90)
    when "Over 120 minutes"
      search_results = Movie.greater_than(120)
    else
      "WHAT?"
    end
    search_results
  end

  def review_average
    reviews.sum(:rating_out_of_ten)/reviews.size
  end

  protected

  # custom validation
  def release_date_is_in_the_past
    if release_date.present?
      errors.add(:release_date, "should be in the past") if release_date > Date.today
    end
  end

end

app/models/review.rb
class Review < ActiveRecord::Base

  belongs_to :user
  belongs_to :movie

  validates :user,
    presence: true

  validates :movie,
    presence: true

  validates :text,
    presence: true

  validates :rating_out_of_ten,
    presence: true,
    numericality: { 
      integer_only: true, 
      greater_than_or_equal_to: 1,
      less_than_or_equal_to: 10
      }

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :reviews, dependent: :destroy
  
  has_secure_password

  validates :email,
    presence: true

  validates :firstname,
    presence: true

  validates :lastname,
    presence: true

  validates :password,
    length: { in: 6..20 }, on: :create

  def full_name
    "#{firstname} #{lastname}"
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_filter :restrict_access, :admin_privileges

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    UserMailer.goodbye_email(@user).deliver_now
    
    redirect_to admin_users_path
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  # easy, application-wide way to check if a user is logged in

  def restrict_access
    unless current_user
      flash[:alert] = "You must be logged in."
      redirect_to new_session_path
    end
  end

  def admin_privileges
    unless current_user.admin
      flash[:alert] = "You do not have these privileges."
      redirect_to welcome_index_path
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all

    @searched_movies = Movie.search(params[:search])
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update(movie_params)
      redirect_to 
    else
      render 'edit'
    end
  end

  def create
    @movie = Movie.new(movie_params)
   
    if @movie.save
      redirect_to movies_path, notice: "#{@movie.title} was submitted successfully!"
    else
      render 'new' # save the already-typed info
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    
    redirect_to movies_path
  end

  private
    def movie_params
      params.require(:movie).permit(:title, :director, 
      :runtime_in_minutes, :description, :poster_image_url, :release_date, :image)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_filter :load_movie, :restrict_access

  def new
    # equivalent to `@review = Review.new(movie_id: @movie.id)`
    @review = @movie.reviews.build
  end

  def create
    @review = @movie.reviews.build(review_params)
    @review.user_id = current_user.id

    if @review.save
      redirect_to @movie, notice: "Review created successfully!"
    else
      render 'new'
    end
  end

  protected

  def load_movie
    @movie = Movie.find(params[:movie_id])
  end

  def review_params
    params.require(:review).permit(:text, :rating_out_of_ten)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    # find the user based on the email in the "email" input field
    user = User.find_by(email: params[:email]) #

    # make sure that user exists and can be authenticated 
    # by the password in the "password" input field
    if user && user.authenticate(params[:password])
      # set the :user_id key in the sessions hash to the user's id
      session[:user_id] = user.id 
      redirect_to movies_path, notice: "Welcome back, #{user.firstname}!"
    else
      flash.now[:alert] = "Log in failed..."
      render :new # show sign up page if user doesn't exist
    end
  end

  def destroy
    # clear session
    session[:user_id] = nil
    # redirect
    redirect_to welcome_index_path, notice: "BAH FELICIA!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:user_id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
   
    if @user.save
      UserMailer.welcome_email(@user).deliver_now
      if current_user.nil?
        session[:user_id] = @user.id # auto log in
        redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!" # show movie listing as home page
      else
        redirect_to admin_users_path, notice: "New user, #{@user.firstname}, was just created." # go back to admin page
      end
    else
      render 'new' # save the already-typed info
    end    
  end

  private
    def user_params
      params.require(:user).permit(:email, :firstname, 
      :lastname, :password, :password_confirmation, :admin)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/users/_form.html.erb
<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %>
        prohibited this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.check_box :admin, class: "filled-in", id: "filled-in-box" %>
    <%= f.label 'Admin?', for: "filled-in-box" %><br>
  </p>

  <p>
    <%= f.label :firstname, 'First Name' %><br>
    <%= f.text_field :firstname %>
  </p>

  <p>
    <%= f.label :lastname, 'Last Name' %><br>
    <%= f.text_field :lastname %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/admin/users/index.html.erb
<h1>Your App Users</h1>

<%= link_to 'New Admin-User', new_admin_user_path %>

<table>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th>Admin</th>
    <th colspan="5"></th>
  </tr>
 
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.firstname, user_profile_path(user) %></td>
      <td><%= user.lastname %></td>
      <td><%= user.email %></td>
      <% if user.admin %>
        <td>Yes</td>
      <% else %>
        <td>No</td>
      <% end %>
      <td><%= link_to 'Show', admin_user_path(user) %></td>
      <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
      <td><%= link_to 'Destroy', admin_user_path(user),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Home', welcome_index_path %>

app/views/admin/users/new.html.erb
<h1>Create New Admin Users</h1>

<%= render 'form' %>

app/views/admin/users/show.html.erb
<p>
  <h1><%= @user.full_name %></h1>
</p>
 
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<div class="admin-privilege">
<% if @user.admin %>
  <p><%= @user.firstname %> has admin privileges.</p>
<% end %>
</div>

<%= link_to 'Back to Your App Users Listing', admin_users_path %>

app/views/layouts/_footer.html.erb
 <footer>
  <small>
    <% if current_user && current_user.admin %>
      Signed in as <%= current_user.full_name %> 🍿 <%= link_to "Log Out", session_path("current"), method: :delete %> 🎥 <%= link_to "Admin Page", admin_users_path %> 🍿 <%= link_to "Your Profile", user_profile_path(current_user) %>
    <% elsif current_user %>
      Signed in as <%= current_user.full_name %> 🍿 <%= link_to "Log Out", session_path("current"), method: :delete %> 🎥 <%= link_to "Your Profile", user_profile_path(current_user) %>
    <% else %>
      <%= link_to "Log In", new_session_path %> 🍿 <%= link_to "Sign Up", new_user_path %>      
    <% end %>
  </small>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RottenMangoes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value) %>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie, html: {multipart: true} do |f| %>

  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@movie.errors.count, "error") %>
        prohibited this movie from being saved:
      </h2>
      <ul>
        <% @movie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :director %><br>
    <%= f.text_field :director %>
  </p>

  <p>
    <%= f.label :runtime_in_minutes %><br>
    <%= f.number_field :runtime_in_minutes %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :poster_image_url %><br>
    <%= f.text_field :poster_image_url %>
  </p>

  <p>
    <%= f.label :image, "Upload Image" %><br>
    <%= f.file_field :image %>
  </p>

  <p>
    <%= f.label :release_date %><br>
    <%= f.date_field :release_date %>
  </p>  

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/movies/_movie.html.erb
<table class="movie-listing-table">
  <tr>
    <td class="info-cell">
      <h1><%= link_to movie.title, movie_path(movie) %></h1>
      <h4>Director: <%= movie.director %></h4>
      <p>Release Date: <%= formatted_date(movie.release_date) %></p>
      <p>Runtime: <%= movie.runtime_in_minutes %> minutes</p>
      <p>Synopsis: <%= movie.description %></p>
      <% if movie.reviews.any? %>
        <p>Average Rating: <%= movie.review_average %>/10</p>
      <% else %>
        <p></p>
      <% end %> 
    </td>
    <td class="poster-cell">
      <p><%= image_tag(movie.image_url(:resized).to_s) %></p>
    </td>
  </tr>
  <tr>
    <td>
      <%= link_to 'Edit', edit_movie_path(movie) %> |
      <%= link_to 'Destroy', movie_path(movie),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
    </td>
  </tr>
</table>

app/views/movies/edit.html.erb
<h1>Edit Movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<h1>Movie Listing</h1>
<div id="new-movie" class="waves-effect waves-light btn">
<%= link_to '<i class="material-icons right">movie</i>New Movie'.html_safe, new_movie_path %>
</div>

<!--   <nav>
    <div class="nav-wrapper">
      <form>
        <div class="input-field">
          <input id="search" type="search" required>
          <label for="search"><i class="material-icons">search</i></label>
          <i class="material-icons">close</i>
        </div>
      </form>
    </div>
  </nav> -->

<%= form_tag movies_path, method: :get, class: "col s12" do %>
  <div class="row">
    <div class="input-field col s6">
      <%= text_field_tag :title, nil, class: "validate" %>
      <%= label_tag :title %>
    </div>
    <div class="input-field col s6">
      <%= text_field_tag :director, nil, class: "validate" %>
      <%= label_tag :director %>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s6">
      <% disabled_option = "Duration" %>
      <%= select_tag(:runtime_in_minutes, options_for_select([disabled_option, "Under 90 minutes", "Between 90 and 120 minutes", "Over 120 minutes"], disabled: disabled_option, selected: disabled_option), class: "duration-dropdown") %>
    </div>
    <div class="col s6">
      <%= submit_tag 'Search', name: nil, class: "waves-effect waves-light btn" %>
    </div>
  </div>
<% end %>

<% if @searched_movies %>
  <% @searched_movies.each do |searched_movie| %>
    <% unless searched_movie.nil? %>
      <ul>
        <li><%= link_to searched_movie.title, movie_path(searched_movie) %></li>
      </ul>
    <% end %>
  <% end %>
<% end %>

<% @movies.each do |movie| %>
  <%= render partial: "movie", locals: {movie: movie} %>
<% end %>

<%= link_to 'Home', welcome_index_path %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p>
  <h1><%= @movie.title %></h1>
</p>
 
<p>
  <strong>Director:</strong>
  <%= @movie.director %>
</p>

<p>
  <strong>Runtime:</strong>
  <%= @movie.runtime_in_minutes %>
</p>

<p>
  <strong>Description:</strong>
  <%= @movie.description %>
</p>

<p>
  <strong>Poster:</strong>
  <%= @movie.poster_image_url %>
</p>

<p>
  <strong>Image Upload:</strong>
  <%= image_tag(@movie.image_url(:resized).to_s) %>
</p>

<p>
  <strong>Release Date:</strong>
  <%= formatted_date(@movie.release_date) %>
</p>

<% if @movie.reviews.any? %>
  <p>
    <strong>Average Review:</strong>
    <td><%= @movie.review_average %>/10</td>
  </p>  
<% end %>  

<hr>

<h1>Reviews:</h1>
<% if current_user %>
  <% @movie.reviews.each do |review| %>
    <%= review.text %>
    <%= review.rating_out_of_ten %>/10
    <small><%= review.user.full_name %></small><br>
  <% end %>
  <p><%= link_to "Write a review!", new_movie_review_path(@movie) %></p>
<% else %>
  <p>Please <%= link_to "Log In", new_session_path %> to see reviews and add your own.</p>
<% end %>



<%= link_to 'Back to Movie Listing', movies_path %>

app/views/reviews/_form.html.erb
<%= form_for([@movie, @review]) do |f| %>

  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@review.errors.count, "error") %>
        prohibited this movie from being saved:
      </h2>
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.label :rating_out_of_ten %><br>
    <%= f.number_field :rating_out_of_ten %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<h1>Write a review for <%= @movie.title %>:</h1>

<%= render 'form' %>

<%= link_to 'Back to Movie', movie_path(@movie) %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %>
        prohibited this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :firstname, 'First Name' %><br>
    <%= f.text_field :firstname %>
  </p>

  <p>
    <%= f.label :lastname, 'Last Name' %><br>
    <%= f.text_field :lastname %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<p>
  <h1><%= @user.full_name %></h1>
</p>
 
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<div class="admin-privilege">
<% if current_user.admin %>
  <% if @user.admin %>
    <p><%= @user.firstname %> has admin privileges.</p>
  <% end %>
<% end %>
</div>

<%= link_to 'Back to Movie Listings', movies_path %>

app/views/welcome/index.html.erb
<h1>Welcome to Rotten Mangoes</h1>
<h2>A Lighthouse Labs Production</h2>

<%= link_to 'See Movies', movies_path %>